# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby-plsql-spec 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby-plsql-spec"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Raimonds Simanovskis"]
  s.date = "2015-01-11"
  s.description = "ruby-plsql-spec is Oracle PL/SQL unit testing framework which is built using Ruby programming language, ruby-plsql library and RSpec testing framework.\n"
  s.email = "raimonds.simanovskis@gmail.com"
  s.executables = ["plsql-spec"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "History.txt",
    "INSTALL-Windows.md",
    "License.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/plsql-spec",
    "examples/source/award_bonus.rb",
    "examples/source/betwnstr.rb",
    "examples/source/remove_rooms_by_name.rb",
    "examples/source/what_is_profiled.rb",
    "examples/spec/award_bonus_spec.rb",
    "examples/spec/betwnstr_spec.rb",
    "examples/spec/database.yml",
    "examples/spec/factories/employee_factory.rb",
    "examples/spec/helpers/inspect_helpers.rb",
    "examples/spec/helpers/oracle_ebs_helpers.rb",
    "examples/spec/helpers/time_helpers.rb",
    "examples/spec/oracle_ebs_spec.rb",
    "examples/spec/remove_rooms_by_name_spec.rb",
    "examples/spec/spec_helper.rb",
    "examples/spec/what_is_profiled_spec.rb",
    "lib/plsql/coverage.rb",
    "lib/plsql/coverage/coverage.css",
    "lib/plsql/coverage/details.html.erb",
    "lib/plsql/coverage/index.html.erb",
    "lib/plsql/coverage/jquery.min.js",
    "lib/plsql/coverage/jquery.tablesorter.min.js",
    "lib/plsql/coverage/proftab.sql",
    "lib/plsql/coverage/rcov.js",
    "lib/plsql/coverage/table_line.html.erb",
    "lib/plsql/spec.rb",
    "lib/plsql/spec/cli.rb",
    "lib/plsql/spec/templates/database.yml",
    "lib/plsql/spec/templates/helpers/inspect_helpers.rb",
    "lib/plsql/spec/templates/helpers/time_helpers.rb",
    "lib/plsql/spec/templates/spec_helper.rb",
    "lib/plsql/spec/version.rb",
    "lib/ruby-plsql-spec.rb",
    "ruby-plsql-spec.gemspec",
    "spec/plsql/coverage_spec.rb",
    "spec/plsql/spec/cli_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/rsim/ruby-plsql-spec"
  s.rubygems_version = "2.4.5"
  s.summary = "Oracle PL/SQL unit testing framework using Ruby and RSpec"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, ["< 4.0", ">= 2.0"])
      s.add_runtime_dependency(%q<rspec-support>, ["< 4.0", ">= 3.1"])
      s.add_runtime_dependency(%q<thor>, ["~> 0.14.2"])
      s.add_runtime_dependency(%q<ruby-plsql>, ["~> 0.5.0"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<ruby-oci8>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["< 4.0", ">= 2.0"])
      s.add_dependency(%q<rspec-support>, ["< 4.0", ">= 3.1"])
      s.add_dependency(%q<thor>, ["~> 0.14.2"])
      s.add_dependency(%q<ruby-plsql>, ["~> 0.5.0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<ruby-oci8>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["< 4.0", ">= 2.0"])
    s.add_dependency(%q<rspec-support>, ["< 4.0", ">= 3.1"])
    s.add_dependency(%q<thor>, ["~> 0.14.2"])
    s.add_dependency(%q<ruby-plsql>, ["~> 0.5.0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<ruby-oci8>, [">= 0"])
  end
end

