# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-plsql-spec}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Raimonds Simanovskis"]
  s.date = %q{2010-10-22}
  s.default_executable = %q{plsql-spec}
  s.description = %q{ruby-plsql-spec is Oracle PL/SQL unit testing framework which is built using Ruby programming language, ruby-plsql library and RSpec testing framework.
}
  s.email = %q{raimonds.simanovskis@gmail.com}
  s.executables = ["plsql-spec"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     ".rspec",
     "Gemfile",
     "History.txt",
     "INSTALL-Windows.markdown",
     "License.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/plsql-spec",
     "examples/source/award_bonus.rb",
     "examples/source/betwnstr.rb",
     "examples/source/remove_rooms_by_name.rb",
     "examples/source/what_is_profiled.rb",
     "examples/spec/award_bonus_spec.rb",
     "examples/spec/betwnstr_spec.rb",
     "examples/spec/database.yml",
     "examples/spec/factories/employee_factory.rb",
     "examples/spec/helpers/inspect_helpers.rb",
     "examples/spec/helpers/oracle_ebs_helpers.rb",
     "examples/spec/helpers/time_helpers.rb",
     "examples/spec/oracle_ebs_spec.rb",
     "examples/spec/remove_rooms_by_name_spec.rb",
     "examples/spec/spec_helper.rb",
     "examples/spec/what_is_profiled_spec.rb",
     "lib/plsql/coverage.rb",
     "lib/plsql/coverage/coverage.css",
     "lib/plsql/coverage/details.html.erb",
     "lib/plsql/coverage/index.html.erb",
     "lib/plsql/coverage/jquery.min.js",
     "lib/plsql/coverage/jquery.tablesorter.min.js",
     "lib/plsql/coverage/proftab.sql",
     "lib/plsql/coverage/rcov.js",
     "lib/plsql/coverage/table_line.html.erb",
     "lib/plsql/spec.rb",
     "lib/plsql/spec/cli.rb",
     "lib/plsql/spec/templates/database.yml",
     "lib/plsql/spec/templates/helpers/inspect_helpers.rb",
     "lib/plsql/spec/templates/helpers/time_helpers.rb",
     "lib/plsql/spec/templates/spec_helper.rb",
     "lib/plsql/spec/version.rb",
     "lib/ruby-plsql-spec.rb",
     "ruby-plsql-spec.gemspec",
     "spec/plsql/coverage_spec.rb",
     "spec/plsql/spec/cli_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rsim/ruby-plsql-spec}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Oracle PL/SQL unit testing framework using Ruby and RSpec}
  s.test_files = [
    "spec/plsql/coverage_spec.rb",
     "spec/plsql/spec/cli_spec.rb",
     "spec/spec_helper.rb",
     "examples/source/award_bonus.rb",
     "examples/source/betwnstr.rb",
     "examples/source/remove_rooms_by_name.rb",
     "examples/source/what_is_profiled.rb",
     "examples/spec/award_bonus_spec.rb",
     "examples/spec/betwnstr_spec.rb",
     "examples/spec/factories/employee_factory.rb",
     "examples/spec/helpers/inspect_helpers.rb",
     "examples/spec/helpers/oracle_ebs_helpers.rb",
     "examples/spec/helpers/time_helpers.rb",
     "examples/spec/oracle_ebs_spec.rb",
     "examples/spec/remove_rooms_by_name_spec.rb",
     "examples/spec/spec_helper.rb",
     "examples/spec/what_is_profiled_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-plsql>, [">= 0.4.4"])
      s.add_runtime_dependency(%q<thor>, [">= 0.14.2"])
      s.add_runtime_dependency(%q<rspec>, [">= 2.0.1"])
    else
      s.add_dependency(%q<ruby-plsql>, [">= 0.4.4"])
      s.add_dependency(%q<thor>, [">= 0.14.2"])
      s.add_dependency(%q<rspec>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<ruby-plsql>, [">= 0.4.4"])
    s.add_dependency(%q<thor>, [">= 0.14.2"])
    s.add_dependency(%q<rspec>, [">= 2.0.1"])
  end
end

